<?php
$pid = Mage::getStoreConfig('giftd_cards/api_settings/partner_token',Mage::app()->getStore());

if ($pid) {
    ?>
<script>
    setTimeout(function(){
        var el = document.createElement("script"); el.id = "giftd-script"; el.async = true;
        el.src = "https://giftd.ru/widgets/js/v2?pid=<?php echo $pid ?>";
        document.getElementsByTagName("head")[0].appendChild(el);
    }, 0);

</script>
<?php
}
?>